### ISSUE TITLE
Update iThenticate API to version 2(latest version)

### ISSUE THREAD

**Issue by touhidurabir** [pkp/plagiarism#56] opened 2024-02-01 07:41 UTC
The current implementation in the plagiarism plugin use the older version of API which maintained no longer . Need to update the API implementation to version 2(latest version) .

**Comment by asmecher** [comment] 2024-02-01 16:22
@touhidurabir, this is a duplicate of https://github.com/pkp/plagiarism/issues/52.

**Closed by asmecher** 2024-02-01 16:22 UTC
Labels: enhancement
